# fly.toml app configuration file generated for meili-commanderscrapper
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'meili-commanderscrapper'
primary_region = 'fra'

[build]
  image = 'getmeili/meilisearch:latest'

[env]
  MEILI_ENV = "production"
  MEILI_DB_PATH = "/meili_data"

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "meili_data"
  destination = "/meili_data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
