name: Update Scryfall JSON

on:
  schedule:
    - cron: "0 0 */1 * *" # Cada 1 día a la medianoche UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Run reducer script
        run: npm run reduce

      - name: Comprobar si hay cambios + commit to repo
        uses: stefanzweifel/git-auto-commit-action@v6