name: Update Typesense Precons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */2 * *" # Cada 2 días a las 6am UTC

jobs:
  update-typesense:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar reducer para generar JSON actualizado
        run: npm run reduce

      - name: Importar nuevas cartas a Typesense
        run: npm run importToTypesense
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}